name: RPi image

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set permissions
        run: |
          chmod -R 777 ./builder
          chmod -R 777 ./builder/assets
          chmod -R 777 ./clover

      - name: Build image
        run: |
          docker run --privileged --rm \
            -v /dev:/dev \
            -v "$(pwd)":/builder/repo \
            -e TRAVIS_TAG="${{ github.event.release.tag_name }}" \
            sfalexrog/img-tool:qemu-update

      - name: Compress image
        run: |
          cd images
          chmod -R 777 .
          zip -9 $(echo *_*).zip *_*
          ls -l
          unzip -l *_*.zip

      - name: Upload image
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v1
        with:
          files: images/*_*.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
